### PR TITLE
Add synchronization primitives

### PR DESCRIPTION
**Pull request by planetis-m**
Examples are kept in a separate folder, although Im thinking of making them later runnableExamples. All but the spinlock depend on std/locks

### CODE REVIEW

**Comment by planetis-m** [comment]
Nim 1.4 lacks broadcast so thats why the barrier test fail.

**Comment by Araq** [comment]
> Nim 1.4 lacks broadcast so thats why the barrier test fail.

So add a version check for these tests or better yet a `when declared(broadcast)`

**Comment by planetis-m** [comment]
Is porting C++ primitives https://github.com/llvm/llvm-project/blob/main/libcxx/include/semaphore doable? I think the lock based semaphore is overly restrictive, however I am not even sure that code can be ported over different compilers/OSes.

**Comment by planetis-m** [comment]
@Araq this is ready for merge.

**Comment by konsumlamm** [comment]
What is the status of this? I know that there is https://github.com/planetis-m/sync, but I think it would still be useful to have some more synchronization primitives here. `latch` is superseded by `waitgroups` afaict. I'm not so sure about `spinlock`, since usually you want to use normal locks instead. The others are pretty common synchronization primitives though.

**Comment by Araq** [comment]
Please split up this PR.

**Comment by planetis-m** [comment]
Sorry I don't have any available time to modernize and split this PR.

**Comment by planetis-m** [comment]
superseeded by #47

**Pull request closed without merging**
